<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    DB::table('banks')->insert([
      ['name' => 'BNI (Bank Negara Indonesia)', 'code' => '009'],
      ['name' => 'BRI (Bank Rakyat Indonesia)', 'code' => '002'],
      ['name' => 'BTN (Bank Tabungan Negara)', 'code' => '200'],
      ['name' => 'Bank Mandiri', 'code' => '008'],
      ['name' => 'BSI (Bank Syariah Indonesia Eks BRI Syariah)', 'code' => '422'],
      ['name' => 'BSI (Bank Syariah Indonesia Eks BNI Syariah)', 'code' => '427'],
      ['name' => 'BSI (Bank Syariah Indonesia Eks Mandiri Syariah)', 'code' => '451'],
      ['name' => 'BCA (Bank Central Asia)', 'code' => '014'],
      ['name' => 'Bank CIMB Niaga', 'code' => '022'],
      ['name' => 'Bank CIMB Niaga Syariah', 'code' => '022'],
      ['name' => 'Bank Muamalat', 'code' => '147'],
      ['name' => 'Bank Danamon', 'code' => '011'],
      ['name' => 'Bank OCBC NISP', 'code' => '028'],
      ['name' => 'Bank Permata', 'code' => '013'],
      ['name' => 'Bank Sinarmas', 'code' => '153'],
      ['name' => 'Bank Mega', 'code' => '426'],
      ['name' => 'Bank BII Maybank', 'code' => '016'],
      ['name' => 'Bank Bukopin', 'code' => '441'],
      ['name' => 'Bank BCA Syariah', 'code' => '536'],
      ['name' => 'Bank Commonwealth', 'code' => '950'],
      ['name' => 'Bank Citibank', 'code' => '031'],
      ['name' => 'Bank BTPN', 'code' => '213'],
      ['name' => 'Bank Jenius BTPN', 'code' => '213'],
      ['name' => 'Bank Panin', 'code' => '019'],
      ['name' => 'Bank Ekspor Indonesia', 'code' => '003'],
      ['name' => 'Bank Arhta Niaga Kencana', 'code' => '020'],
      ['name' => 'Bank Buana IND', 'code' => '023'],
      ['name' => 'Bank Artha Graha', 'code' => '037'],
      ['name' => 'Bank Bank Multicor', 'code' => '036'],
      ['name' => 'Bank Sumitomo Mitsui Indonesia', 'code' => '045'],
      ['name' => 'Bank DBS Indonesia', 'code' => '046'],
      ['name' => 'Bank Resona Perdania', 'code' => '047'],
      ['name' => 'Bank Mizuho Indonesia', 'code' => '048'],
      ['name' => 'Bank Standard Chartered', 'code' => '050'],
      ['name' => 'Bank Capital Indonesia', 'code' => '054'],
      ['name' => 'Bank ABN Amro', 'code' => '052'],
      ['name' => 'Bank Keppel Tatlee Buana', 'code' => '053'],
      ['name' => 'Bank UOB Indonesia', 'code' => '023'],
      ['name' => 'Bank Capital Indonesia', 'code' => '054'],
      ['name' => 'Bank Woori Indonesia', 'code' => '068'],
      ['name' => 'Bank Bumi Artha', 'code' => '076'],
      ['name' => 'Bank Ekonomi', 'code' => '087'],
      ['name' => 'Bank Haga', 'code' => '089'],
      ['name' => 'Bank IFI', 'code' => '093'],
      ['name' => 'Bank Century/Bank J Trust Indonesia', 'code' => '095'],
      ['name' => 'Bank Mayapada', 'code' => '097'],
      ['name' => 'Bank Nusantara Parahyangan', 'code' => '145'],
      ['name' => 'Bank Swadesi', 'code' => '146'],
      ['name' => 'Bank Mestika', 'code' => '151'],
      ['name' => 'Bank Metro Express', 'code' => '152'],
      ['name' => 'Bank Maspion', 'code' => '157'],
      ['name' => 'Bank Hagakita', 'code' => '159'],
      ['name' => 'Bank Ganesha', 'code' => '161'],
      ['name' => 'Bank Windu Kentjana', 'code' => '162'],
      ['name' => 'Bank Harmoni Internasional', 'code' => '166'],
      ['name' => 'Bank QNB Kesawan (Bank QNB)', 'code' => '167'],
      ['name' => 'Bank Swaguna', 'code' => '405'],
      ['name' => 'Bank Bisnis Internasional', 'code' => '459'],
      ['name' => 'Bank Sri Partha', 'code' => '466'],
      ['name' => 'Bank DKI Jakarta', 'code' => '111'],
      ['name' => 'Bank Jabar (Jawa Barat)', 'code' => '110'],
      ['name' => 'Bank Jateng (Jawa Tengah)', 'code' => '113'],
      ['name' => 'Bank Jatim (Jawa Timur)', 'code' => '114'],
      ['name' => 'BPD DIY (Yogyakarta)', 'code' => '112'],
      ['name' => 'BPD Jambi', 'code' => '115'],
      ['name' => 'BPD Aceh', 'code' => '116'],
      ['name' => 'BPD Aceh Syariah', 'code' => '116'],
      ['name' => 'Bank Sumut (Sumatera Utara)', 'code' => '117'],
      ['name' => 'Bank Nagari (Bank Sumbar)', 'code' => '118'],
      ['name' => 'Bank Riau Kepri', 'code' => '119'],
      ['name' => 'Bank Sumber Babel', 'code' => '120'],
      ['name' => 'Bank Lampung', 'code' => '121'],
      ['name' => 'Bank Kalsel (Kalimantan Selatan)', 'code' => '122'],
      ['name' => 'Bank Kalbar (Kalimantan Barat)', 'code' => '123'],
      ['name' => 'Bank Kaltim Tara (Kalimantan Timur dan Utara)', 'code' => '124'],
      ['name' => 'Bank Kalteng (Kalimantan Tengah)', 'code' => '125'],
      ['name' => 'Bank Sulselbar (Sulawesi Selatan dan Barat)', 'code' => '126'],
      ['name' => 'Bank Sulutgo (Sulawesi Utara dan Gorontalo)', 'code' => '127'],
      ['name' => 'Bank NTP', 'code' => '128'],
      ['name' => 'Bank NTB Syariah', 'code' => '128'],
      ['name' => 'Bank BPD Bali', 'code' => '129'],
      ['name' => 'Bank NTT', 'code' => '130'],
      ['name' => 'Bank Maluku Malut', 'code' => '131'],
      ['name' => 'Bank Papua', 'code' => '132'],
      ['name' => 'Bank Bengkulu', 'code' => '133'],
      ['name' => 'Bank Sulteng (Sulawesi Tengah)', 'code' => '134'],
      ['name' => 'Bank Sultra', 'code' => '135'],
      ['name' => 'BPD Banten', 'code' => '137'],
    ]);
  }
}
